#!/bin/bash
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation" 1
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Button" 2
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Timeout" 200
xinput set-prop "TPPS/2 IBM TrackPoint" "Evdev Wheel Emulation Axes" 6 7 4 5
xinput set-prop "TPPS/2 IBM TrackPoint" "Device Accel Constant Deceleration" 0.75
xscreensaver &
(sleep 2 && xmodmap ~/.Xmodmap) &
xrdb -merge ~/.Xdefaults
xset +fp /usr/share/fonts/local
xset fp rehash
setxkbmap us -variant colemak
setxkbmap -option terminate:ctrl_alt_bksp
setxkbmap -option ctrl:nocaps
xset b off
xbindkeys &
opera &
urxvt &
conky &
devmon --exec-on-drive "pcmanfm %d" &
exec dbus-launch goomwwm
